---
- name: Deploy nginx
  hosts: web
  become: yes
  
  tasks:
  - name: Ensure nginx is present
    apt:
      name: nginx
      update_cache: yes
      state: present
      
   - name: Ensure nginx is started
     service:
       name: nginx
       state: started